### ISSUE TITLE
NPE when importing a project which hasn't build yet with Maven

### ISSUE THREAD

**Issue by nickstolwijk** [hennejg/m2e-assertj#1]
I have found an NPE if you try to use the M2E connector while not having done a build with the assertj generator enabled. For example, when pulling a project to which it has been added. It seems the connector assumes the target dir is always there and when it is not, an NPE arises.

Description Resource    Path    Location    Type
null (org.assertj:assertj-assertions-generator-maven-plugin:2.0.0:generate-assertions:default:generate-test-sources)

java.lang.NullPointerException
    at org.levigo.m2e.assertj.internal.AssertJBuildParticipant.cleanTargetFolder(AssertJBuildParticipant.java:229)
    at org.levigo.m2e.assertj.internal.AssertJBuildParticipant.build(AssertJBuildParticipant.java:147)
    at org.eclipse.m2e.core.internal.builder.MavenBuilderImpl.build(MavenBuilderImpl.java:137)

**Comment by hennejg** [comment]
Thanks for the report - should be fixed in 0.5.0
